In [1]:
take = 1

# Description

Script to run the agent on the hardware

0. Description
1. Imports
2. Paths
3. Configuration
4. Functions
5. Creation
6. Run on Hardware
7. Save recorded Data


# Specification

In [2]:
control_rate = 75 #Hz
dt = 0.1
model_number = 999
max_limit = 0.0001 #0.0001 0.000085
R1 = 1
R2 = 0.005
R_success = 250
reality_distance_threshold = 0.0075

reality_horizon = 3000

# Imports

In [3]:
# General imports
import os
import time
import datetime
from os.path import expanduser
import pandas
import pickle
import json
import numpy
from matplotlib import pyplot as plt

# rllib imports
import ray
import ray.rllib.agents.ppo as ppo
from ray.tune.registry import get_trainable_cls
from ray.tune.registry import register_env
from ray.rllib.env import MultiAgentEnv
from ray.rllib.env.base_env import _DUMMY_AGENT_ID
from ray.rllib.evaluation.worker_set import WorkerSet
from ray.rllib.policy.sample_batch import DEFAULT_POLICY_ID
from ray.rllib.utils.deprecation import deprecation_warning

# Gym imports
from gym.envs.robotics.ur10 import randomize
from gym.envs.robotics.ur10 import pos_randomize
from gym.envs.robotics import ur10_noisy_pd_env_mh
from gym.envs.robotics import ur10_sim2real_pos_env
from gym import utils
from gym.envs.robotics import rotations, robot_custom_env_mh, utils
from gym.envs.robotics import ur10_force_env_3
from gym.envs.robotics import ur10_force_env

# MuJoCo imports
import mujoco_py

# ROS imports
import rospy
from sensor_msgs.msg import JointState
from std_msgs.msg import Float64MultiArray
from std_msgs.msg import String
from geometry_msgs.msg import WrenchStamped
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from realsense2_camera.msg import CustomVector
from realsense2_camera.msg import EstimatedPose

In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_c

# Paths

In [4]:
HOME_PATH = os.getenv("HOME")
PROJECT_PATH = os.path.join(*[HOME_PATH, "DRL_AI4RoMoCo"])
SAVE_PATH = os.path.join(*[PROJECT_PATH, "code", "data","TEST_Reality"])

#XML_MODEL_PATH = os.path.join(*[HOME_PATH, "DRL_AI4RoMoCo", "code", "environment","UR10_single","ur10_heg.xml"])   #Force
XML_MODEL_PATH = os.path.join(*[HOME_PATH, "DRL_AI4RoMoCo", "code", "environment","UR10_single_position","ur10_heg_position.xml"])   #Position

env_config = "reality_config_force.yml"
#checkpoint_number = 4950
#model = "PPO_NoisyPositionEnv_0_2020-09-18_20-14-55ej_cw9mo"
control_type = env_config.split("_")[2].split(".")[0]

ENV_CONFIG = os.path.join(*[HOME_PATH, "AGENT_TESTS", env_config])
#ENV_CONFIG = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_ForceEnv_0_2020-09-10_15-29-51_j1bhegb", config])

# Configuration

Hardware - Environment (ROS)

In [5]:
actual_q = numpy.zeros(6,)
ft_values = numpy.zeros(6,)

Simulation - Environment (MuJoCo, Gym)

In [6]:
goal = numpy.array([0.69423743, -0.83110109,  1.17388998, -1.57161506,  0.02185773, -3.14102438])
reward_type = "dense"
distance_threshold = 0.002
fail_threshold = 0.25
punish_force = False
punish_force_thresh = 20
punish_force_factor = 0.001
print(goal)

[ 0.69423743 -0.83110109  1.17388998 -1.57161506  0.02185773 -3.14102438]


In [7]:
initial_qpos_simpheg_conf2 = numpy.array([0, -1.3, 2.1, -0.80, 1.5708, 0])
randomize_kwargs = {
    'var_mass':     0,#0.5,
    'var_damp':     0,#0.5,
    'var_fr':       0,#0.5,
    'var_grav_x_y': 0,#0.5,
    'var_grav_z':   0,#1,
    'var_body_pos': 0,#0.05,
    'var_body_rot': 0,
}

Agent (ray, tune, rllib)

In [8]:
checkpoint_model1 = os.path.join(*[HOME_PATH, "DRL_SetBot-RearVentilation", "final_models",
                            "model1", "checkpoint-2120"])
checkpoint_model2 = os.path.join(*[HOME_PATH, "DRL_SetBot-RearVentilation", "final_models",
                            "model2", "checkpoint-3440"])
checkpoint_model3 = os.path.join(*[HOME_PATH, "DRL_SetBot-RearVentilation", "final_models",
                            "model3", "checkpoint-3030"])
checkpoint_model4 = os.path.join(*[HOME_PATH, "DRL_SetBot-RearVentilation", "final_models",
                            "model4", "checkpoint-3590"])
checkpoint_model5 = os.path.join(*[HOME_PATH, "DRL_SetBot-RearVentilation", "final_models",
                            "model5", "checkpoint-4410"])

#checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyVaryEnv_0_2020-09-15_13-53-11d046bzlf", "checkpoint_2675", "checkpoint-2675"]) #Fail
#checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyVaryEnv_0_2020-09-16_20-33-05bjvfub2b", "checkpoint_4275", "checkpoint-4275"]) #works
#checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyPositionEnv_0_2020-09-18_20-14-55ej_cw9mo", "checkpoint_4950", "checkpoint-4950"]) #Position
#checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyEnv_0_2020-09-22_19-50-24bt7wx44r", "checkpoint_1175", "checkpoint-1175"]) # New and corrective
#checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyEnv_0_2020-09-22_13-53-53m9s7_v8d", "checkpoint_220", "checkpoint-220"]) # New and corrective
#checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyEnv_0_2020-09-17_16-12-44a70jmqsn", "checkpoint_3150", "checkpoint-3150"]) #works
#checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyCorEnv_0_2020-09-22_12-24-02irctporb", "checkpoint_75", "checkpoint-75"]) # CorEnv

#scheckpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_StaticEnv_0_2020-09-24_08-39-32jdnl7ykv", "checkpoint_810", "checkpoint-810"]) # Static25
checkpoint_lars = os.path.join(*[HOME_PATH, "AGENT_TESTS", "PPO_NoisyEnv_0_2020-09-24_09-07-22vaoju9fy", "checkpoint_780", "checkpoint-780"]) # Noisy25
#checkpoint_lars = checkpoint_model4    # Gutes Modell


In [9]:
def update_checkpoint_for_rollout(checkpoint_path):
    with open(checkpoint_path, "rb") as f:
        extra_data = pickle.load(f)
    if not "trainer_state" in extra_data:
        extra_data["trainer_state"] = {}
        with open(checkpoint_path, 'wb') as f:
            pickle.dump(extra_data, f)

checkpoint = checkpoint_lars
update_checkpoint_for_rollout(checkpoint)
checkpoint

'/home/lars/AGENT_TESTS/PPO_NoisyEnv_0_2020-09-24_09-07-22vaoju9fy/checkpoint_780/checkpoint-780'

In [10]:
config = {}
    # Load configuration from checkpoint file.
config_dir = os.path.dirname(checkpoint)
config_path = os.path.join(config_dir, "params.pkl")
# Try parent directory.
if not os.path.exists(config_path):
    config_path = os.path.join(config_dir, "../params.pkl")
if os.path.exists(config_path):
    print("Config found!")
    with open(config_path, "rb") as f:
            config = pickle.load(f)
            
config['num_workers'] = 2
config['num_gpus'] = 1

Config found!


In [11]:
config

{'env': 'NoisyEnv',
 'seed': 1794,
 'num_workers': 2,
 'num_envs_per_worker': 1,
 'num_gpus': 1,
 'gamma': 0.99,
 'lr': 0.0003,
 'horizon': 500,
 'soft_horizon': False,
 'train_batch_size': 11000,
 'callbacks': {'on_episode_start': None,
  'on_episode_step': None,
  'on_episode_end': None,
  'on_postprocess_traj': None},
 'model': {'use_lstm': False,
  'lstm_cell_size': 128,
  'fcnet_hiddens': [256, 256]},
 'tf_session_args': {'allow_soft_placement': True}}

# Functions

Helper Functions

In [12]:
def normalize_rad(angles):
    angles = numpy.array(angles)
    angles = angles % (2*numpy.pi)
    angles = (angles + 2*numpy.pi) % (2*numpy.pi)
    for i in range(len(angles)):
        if (angles[i] > numpy.pi):
            angles[i] -= 2*numpy.pi
    return angles

def get_obs():
    set_state(actual_q)
    for i in range(10):
        viewer.render()
    #print(ft_values)
    x_pos = sim.data.get_body_xpos("gripper_dummy_heg")
    x_mat = sim.data.get_body_xmat("gripper_dummy_heg")
    rpy =  normalize_rad(rotations.mat2euler(x_mat))
    #print(x_pos, rpy)

    obs = numpy.concatenate([
                x_mat.dot(x_pos-goal[:3]), x_mat.dot(normalize_rad(rpy-goal[3:])), ft_values.copy()
            ])
    return obs

def get_dq(dx):
    jacp = sim.data.get_body_jacp(name="gripper_dummy_heg").reshape(3, 6)
    jacr = sim.data.get_body_jacr(name="gripper_dummy_heg").reshape(3, 6)
    jac = numpy.vstack((jacp, jacr))
    dq = numpy.linalg.lstsq(jac, dx)[0].reshape(6, )
    return dq

def go_smooth(q):
    rate = rospy.Rate(125)
    dq = q - actual_q
    while numpy.linalg.norm(dq)>0.005:
        dq = q - actual_q
        dq_ = numpy.clip(dq, -0.0001, 0.0001)
        control(ctrl_q+dq_)
        rate.sleep()
    control(q)
    
def set_state(qpos):
    #assert qpos.shape == (model.nq,)
    old_state = sim.get_state()
    new_state = mujoco_py.MjSimState(old_state.time, qpos, old_state.qvel,
                                     old_state.act, old_state.udd_state)
    sim.set_state(new_state)
    sim.forward()
    
def keep_going(steps, num_steps, episodes, num_episodes):
    """Determine whether we've collected enough data"""
    # if num_episodes is set, this overrides num_steps
    if num_episodes:
        return episodes < num_episodes
    # if num_steps is set, continue until we reach the limit
    if num_steps:
        return steps < num_steps
    # otherwise keep going forever
    return True

ROS

In [13]:
# ROS callback functions
def q_callback(data):
    '''Callback for the joint angles, velocities and accelerations'''
    global actual_q
    global actual_qd
    global actual_qdd
    actual_q = numpy.array(data.position)[[2,1,0,3,4,5]]
    actual_qd = numpy.array(data.velocity)[[2,1,0,3,4,5]]
    actual_qdd = numpy.array(data.effort)[[2,1,0,3,4,5]]
    set_state(actual_q)
    viewer.render()
    
def ft_callback(data):
    '''Callback for the Robotiq FT300 force torque values'''
    global ft_values
    ft_values = 1 * numpy.array([data.wrench.force.x, data.wrench.force.y, data.wrench.force.z, data.wrench.torque.x, \
                            data.wrench.torque.y, data.wrench.torque.z])
    
def pose_callback(data):
    '''Callback for the Intel Realsense D435i and OpenCV charuco pose estimation'''
    global pose
    pose = numpy.array([data.tx, data.ty, data.tz, data.rx, data.ry, data.rz])
    
def observation_callback(data):
    '''Callback for the entire observation array (same as in simulation)'''
    global observations
    observations = numpy.array(data.data)
    
def check_ROS_topics():
    '''Listens to all required ROS topics and checks if each of them is online and sending'''
    check_jointstates = []
    check_ft300_force_torque = []
    check_observations = []
    check_pose_estimation = []
    
    for i in range(5):
        check_jointstates.append(actual_q)
        check_ft300_force_torque.append(ft_values)
        check_observations.append(observations)
        check_pose_estimation.append(pose)
        time.sleep(0.5)
        
    topics = ["/joint_states", "/ft300_force_torque", "/observation", "/pose_estimation"]
    topics_dict = {
        "/joint_states" : check_jointstates,
        "/ft300_force_torque" : check_ft300_force_torque,
        "/observation" : check_observations,
        "/pose_estimation" : check_pose_estimation
    }
    
    for topic in topics:
        if not topics_dict[topic]:
            print("ERROR: {} is offline or not sending".format(topic))
        else:
            print("SUCCESS: {} is online and sending".format(topic))

In [14]:
def goal_distance(obs, goal):
    '''Compute distance between TCP and Goal'''
    obs = obs[:6]
    assert obs.shape == goal.shape
    return numpy.linalg.norm(obs*numpy.array([1, 1, 1, 0.3, 0.3, 0.3]), axis=-1)

def compute_reward(obs, goal):
    d = goal_distance(obs,goal)
    f = numpy.absolute(obs[7]) + numpy.absolute(obs[8]) + numpy.absolute(obs[9])
    rew = R1 * (-d) + R2 *(-f)
    return rew
'''
def is_success(obs, goal):
    d = goal_distance(obs,goal)
    if d < distance_threshold:
        return True
    else:
        return False
'''
def is_success(obs):
    distance = numpy.absolute(obs[0]) + numpy.absolute(obs[1]) + numpy.absolute(obs[2])
    if distance < reality_distance_threshold:
        return True
    else:
        return False

In [15]:
# ROS control commands
def control(q):
    '''Controlling the Universal Robot UR10 JointGroupPositionController'''
    global ctrl_q
    command = Float64MultiArray()
    command.data = q
    control_publisher.publish(command)
    ctrl_q = q.copy()
    
def traj_control(q):
    #dt = 0.025
    global ctrl_q
    command = JointTrajectory()
    point = JointTrajectoryPoint()
    
    #command.header.stamp = rospy.Time.now()
    #command.header.frame_id = "DRL_UR10"
    #command.joint_names = ["elbow_joint", "shoulder_lift_joint", "shoulder_pan_joint", "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
    
    #command.header.stamp = rospy.Time.now()
    command.header.frame_id = "DRL_UR10"
    command.joint_names.append("shoulder_pan_joint")
    command.joint_names.append("shoulder_lift_joint")
    command.joint_names.append("elbow_joint")
    command.joint_names.append("wrist_1_joint")
    command.joint_names.append("wrist_2_joint")
    command.joint_names.append("wrist_3_joint")
    

    point.positions.append(q[0])
    point.positions.append(q[1])
    point.positions.append(q[2])
    point.positions.append(q[3])
    point.positions.append(q[4])
    point.positions.append(q[5])
    
    command.points.append(point)
    command.points[0].time_from_start=rospy.Duration.from_sec(dt)
    
    traj_control_publisher.publish(command)
    ctrl_q = q.copy()
    
def static_approach():
    
    waypoint0 = numpy.array([1.6256170272827148, -0.9155753294574183, 1.5307668447494507, -0.6977546850787562, 1.5475375652313232, 0.011224725283682346])[[2,1,0,3,4,5]]
    waypoint1 = numpy.array([2.47381329536438, -1.4324410597430628, 1.5743204355239868, -1.0292657057391565, 1.5910834074020386, 0.011859889142215252])[[2,1,0,3,4,5]]
    waypoint2 = numpy.array([2.519468069076538, -1.6841238180743616, 0.13313426077365875, -0.8226664702044886, 1.7688652276992798, 0.014099815860390663])[[2,1,0,3,4,5]]
    waypoint3 = numpy.array([2.1001405715942383, -1.3000262419330042, 7.190534961409867e-05, -0.7999804655658167, 1.5709056854248047, -3.5587941304981996e-05])[[2,1,0,3,4,5]]
    
    dt_static = 2
    command = JointTrajectory()
    point0 = JointTrajectoryPoint()
    point1 = JointTrajectoryPoint()
    point2 = JointTrajectoryPoint()
    point3 = JointTrajectoryPoint()
    
    command.header.stamp = rospy.Time.now()
    command.header.frame_id = "DRL_UR10"
    command.joint_names.append("shoulder_pan_joint")
    command.joint_names.append("shoulder_lift_joint")
    command.joint_names.append("elbow_joint")
    command.joint_names.append("wrist_1_joint")
    command.joint_names.append("wrist_2_joint")
    command.joint_names.append("wrist_3_joint")
    
    point0.positions.append(waypoint0[0])
    point0.positions.append(waypoint0[1])
    point0.positions.append(waypoint0[2])
    point0.positions.append(waypoint0[3])
    point0.positions.append(waypoint0[4])
    point0.positions.append(waypoint0[5])
    
    #command.points.append(point0)
    
    point1.positions.append(waypoint1[0])
    point1.positions.append(waypoint1[1])
    point1.positions.append(waypoint1[2])
    point1.positions.append(waypoint1[3])
    point1.positions.append(waypoint1[4])
    point1.positions.append(waypoint1[5])
    
    command.points.append(point1)
    command.points[0].time_from_start=rospy.Duration.from_sec(dt_static)
    
    point2.positions.append(waypoint2[0])
    point2.positions.append(waypoint2[1])
    point2.positions.append(waypoint2[2])
    point2.positions.append(waypoint2[3])
    point2.positions.append(waypoint2[4])
    point2.positions.append(waypoint2[5])
    
    command.points.append(point2)
    command.points[1].time_from_start=rospy.Duration.from_sec(2*dt_static)
    
    point3.positions.append(waypoint3[0])
    point3.positions.append(waypoint3[1])
    point3.positions.append(waypoint3[2])
    point3.positions.append(waypoint3[3])
    point3.positions.append(waypoint3[4])
    point3.positions.append(waypoint3[5])
    
    command.points.append(point3)
    command.points[2].time_from_start=rospy.Duration.from_sec(2.5*dt_static)
    
    traj_control_publisher.publish(command)
    
def ft_zero():
    '''Zeroes the Robotiq FT300 force torque sensor by sending an ur_script via UR Secondary Interface'''
    zero_sensor_urscript = 'sec ft_set_zero():' + '\n' + '\t' + 'if(socket_open("127.0.0.1", 63350, "acc")):' \
          + '\n' + '\t' + '\t' + 'socket_send_string("SET ZRO", "acc")' \
         + '\n' + '\t' + '\t' + 'socket_close("acc")' + '\n' + '\t' + 'end' + '\n' + 'end' + '\n'
    ft_zero_publisher.publish(zero_sensor_urscript)

# Creation

Simulation Environment (Gym)

In [16]:
model = mujoco_py.load_model_from_path(XML_MODEL_PATH)
sim = mujoco_py.MjSim(model)
q_init = numpy.array([0, -1.3, 2.1, -0.80, 1.5708, 0.0])

ctrl_q = q_init
set_state(q_init)

viewer = mujoco_py.MjViewer(sim)
viewer.render()

Creating window glfw


In [17]:
x_pos = sim.data.get_body_xpos("gripper_dummy_heg")
x_mat = sim.data.get_body_xmat("gripper_dummy_heg")
rpy =  normalize_rad(rotations.mat2euler(x_mat))
print(x_pos, rpy)

[ 0.57243453 -0.83605904  1.17575472] [-1.57079633e+00  3.67320510e-06  3.14159265e+00]


In [18]:
if control_type == "force":
    class Ur10HegRandForceEnv(ur10_noisy_pd_env_mh.Ur10Env):
        def __init__(self, env_config):
            model_xml_path = os.path.join(*[PROJECT_PATH, "code", "environment", "UR10_Force_Randomized", "ur10_assembly_setup_rand_temp_{}.xml".format(env_config.worker_index)])
            randomize.randomize_ur10_xml(worker_id = env_config.worker_index)
            ur10_noisy_pd_env_mh.Ur10Env.__init__(
                self, ENV_CONFIG, model_xml_path = model_xml_path, worker_id=env_config.worker_index
            )
            #utils.EzPickle.__init__(self)
    register_env("NoisyEnv", lambda config: Ur10HegRandForceEnv(config))
    print("FORCE CONTROL")
elif control_type == "position":
    class Ur10HegRandPositionEnv(ur10_sim2real_pos_env.Ur10Env):
        def __init__(self, env_config):
            model_xml_path = os.path.join(*[PROJECT_PATH, "code", "environment", "UR10_Position_Randomized", "ur10_assembly_setup_rand_temp_{}.xml".format(env_config.worker_index)])
            pos_randomize.randomize_ur10_xml(worker_id = env_config.worker_index)
            ur10_sim2real_pos_env.Ur10Env.__init__(
                self, ENV_CONFIG, model_xml_path = model_xml_path, worker_id=env_config.worker_index
            )
            #utils.EzPickle.__init__(self)
    register_env("NoisyPositionEnv", lambda config: Ur10HegRandPositionEnv(config))
    print("POSITION CONTROL")
else:
    print("ERROR for control_type:", control_type)

FORCE CONTROL


Agent

In [19]:
ray.init()
cls = get_trainable_cls("PPO")

2020-09-25 10:36:34,818	INFO resource_spec.py:212 -- Starting Ray with 15.48 GiB memory available for workers and up to 7.76 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2020-09-25 10:36:35,445	INFO services.py:1083 -- View the Ray dashboard at localhost:8265


In [20]:
#agent = cls(env="RandomizedEnv", config=config)
agent = cls(config=config)
agent.restore(checkpoint)

2020-09-25 10:36:36,865	INFO trainer.py:420 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
2020-09-25 10:36:36,947	INFO trainer.py:580 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
/home/lars/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


(pid=25978) /home/lars/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=25978)   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
(pid=25978) /home/lars/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=25978)   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
(pid=25978) /home/lars/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
(pid=25978)   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
(pid=25978) /home/lars/.l

2020-09-25 10:36:43,536	WARNING trainable.py:210 -- Getting current IP.
2020-09-25 10:36:43,537	INFO trainable.py:416 -- Restored on 10.180.134.127 from checkpoint: /home/lars/AGENT_TESTS/PPO_NoisyEnv_0_2020-09-24_09-07-22vaoju9fy/checkpoint_780/checkpoint-780
2020-09-25 10:36:43,538	INFO trainable.py:423 -- Current state after restoring: {'_iteration': 780, '_timesteps_total': None, '_time_total': 83469.00706005096, '_episodes_total': 55618}


(pid=25975) In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
(pid=25975) The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
(pid=25975) In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
(pid=25975) The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
(pid=25975) In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
(pid=25975) In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
(pid=25975) The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases lat

In [21]:
print(ray)
print(get_trainable_cls)
print(ray.tune.registry)
clss = get_trainable_cls("PPO")

<module 'ray' from '/home/lars/.local/lib/python3.6/site-packages/ray/__init__.py'>
<function get_trainable_cls at 0x7f5b6de9c048>
<module 'ray.tune.registry' from '/home/lars/.local/lib/python3.6/site-packages/ray/tune/registry.py'>


ROS-nodes

In [22]:
rospy.init_node("DRL_AI4RoMoCo", anonymous=True)
rospy.Subscriber("/joint_states", JointState, q_callback)
rospy.Subscriber("/ft300_force_torque", WrenchStamped, ft_callback)
rospy.Subscriber("/pose_estimation", EstimatedPose, pose_callback)
rospy.Subscriber("/observation", CustomVector, observation_callback)
#control_publisher = rospy.Publisher("/joint_group_position_controller/command", Float64MultiArray, queue_size=1)
traj_control_publisher = rospy.Publisher("/pos_traj_controller/command", JointTrajectory, queue_size=1)
ft_zero_publisher = rospy.Publisher("/ur_hardware_interface/script_command", String, queue_size=1)

#rate = rospy.Rate(1)
rate = rospy.Rate(control_rate)

(pid=25975) /home/lars/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=25975)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
(pid=25978) /home/lars/gym/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
(pid=25978)   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


Data structures for storing and saving data

In [23]:
observations

array([ 0.12803569,  0.00244428,  0.00488203, -0.00085671, -0.00045745,
       -0.02183218,  0.04      ,  0.08      ,  0.02      ,  0.004     ,
        0.003     ,  0.001     ])

In [24]:
observations_rec = []
poses_rec = []
ft_values_rec = []
q_rec = []
qd_rec = []
rewards_rec = []
step = 0

# Run On Hardware

In [25]:
agent.compute_action([0,0,0,0,0,0,0,0,0,0,0,0])

array([-1.        , -0.65675116,  1.        , -0.16475676, -0.59990036,
        0.10499126], dtype=float32)

In [ ]:
done = False
ft_zero()
#max_limit = 0.00075

time.sleep(2.5)
while not done:
    obs = get_obs()
    action = agent.compute_action(obs)
    for i in range(1):
        dx = max_limit * action.copy()
        rot_mat = sim.data.get_body_xmat('gripper_dummy_heg')
        dx_ = numpy.concatenate([rot_mat.dot(dx[:3]), rot_mat.dot(dx[3:])])  ## transform to right coordinate system
        dq  = get_dq(dx_)
        q = ctrl_q + dq
        traj_control(q)
        print(observations[6:9])
        observations_rec.append(observations)
        poses_rec.append(pose)
        ft_values_rec.append(ft_values)
        q_rec.append(actual_q)
        qd_rec.append(actual_qd)
        rewards_rec.append(compute_reward(obs, goal))
        step += 1
    if is_success(obs) or step >= reality_horizon:
        rewards_rec.append(R_success)
        break
    rate.sleep()

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[0.09       0.09       0.18000001]
[0.09       0.09       0.18000001]
[0.06       0.13       0.27000001]
[0.06       0.13       0.27000001]
[-0.03  0.04  0.16]
[-0.03  0.04  0.16]
[-0.03  0.04  0.16]
[-0.05  0.07  0.08]
[-0.05  0.07  0.08]
[0.13 0.03 0.07]
[0.13 0.03 0.07]
[0.13 0.03 0.07]


/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-0.22        0.25        0.23999999]
[-0.22        0.25        0.23999999]
[-0.22        0.25        0.23999999]
[0.58999997 0.18000001 0.05      ]
[0.58999997 0.18000001 0.05      ]
[0.15000001 0.16       0.05      ]
[0.15000001 0.16       0.05      ]
[0.15000001 0.16       0.05      ]
[0.04       0.46000001 0.28      ]
[0.04       0.46000001 0.28      ]
[ 0.34999999  0.23       -0.18000001]
[ 0.34999999  0.23       -0.18000001]
[-0.13        0.47        0.25999999]
[-0.13        0.47        0.25999999]
[-0.13        0.47        0.25999999]
[0.69999999 0.31999999 0.02      ]
[0.69999999 0.31999999 0.02      ]
[0.12       0.50999999 0.12      ]
[0.12       0.50999999 0.12      ]
[ 0.44  0.2  -0.01]
[ 0.44  0.2  -0.01]
[ 0.44  0.2  -0.01]
[0.18000001 0.33000001 0.02      ]
[0.18000001 0.33000001 0.02      ]
[0.18000001 0.33000001 0.02      ]
[0.09 0.16 0.07]
[ 0.15000001 -0.06        0.08      ]
[ 0.15000001 -0.06        0.08      ]
[ 0.15000001 -0.06        0.08      ]
[-0.02        0

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[0.02 0.17 0.2 ]
[0.02 0.17 0.2 ]
[ 0.33000001  0.15000001 -0.02      ]
[ 0.33000001  0.15000001 -0.02      ]
[0.01 0.34 0.19]
[0.01 0.34 0.19]
[ 0.22       -0.25999999  0.1       ]
[ 0.22       -0.25999999  0.1       ]
[ 0.22       -0.25999999  0.1       ]
[-0.16        0.58999997  0.20999999]
[-0.16        0.58999997  0.20999999]
[-0.16        0.58999997  0.20999999]
[ 0.06  0.56 -0.06]
[ 0.06  0.56 -0.06]
[-0.09        0.60000002  0.27000001]
[-0.09        0.60000002  0.27000001]
[-0.09        0.60000002  0.27000001]
[ 0.06  0.16 -0.01]
[ 0.06  0.16 -0.01]
[0.03 0.28 0.23]
[0.03 0.28 0.23]
[0.2        0.17       0.15000001]
[0.2        0.17       0.15000001]
[0.2        0.17       0.15000001]
[0.1        0.43000001 0.25999999]
[0.1        0.43000001 0.25999999]
[0.1        0.43000001 0.25999999]
[-0.25  0.06  0.34]
[-0.25  0.06  0.34]
[-0.04  0.13  0.1 ]
[-0.04  0.13  0.1 ]
[-0.04  0.13  0.1 ]
[ 0.40000001  0.15000001 -0.05      ]
[ 0.40000001  0.15000001 -0.05      ]
[-0.06        

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[0.18000001 0.28999999 0.20999999]
[-0.05        0.23999999  0.28999999]
[-0.05        0.23999999  0.28999999]
[-0.05        0.23999999  0.28999999]
[-0.05        0.23999999  0.28999999]
[ 0.37 -0.12 -0.22]
[ 0.37 -0.12 -0.22]
[0.28 0.09 0.02]
[0.28 0.09 0.02]
[0.28 0.09 0.02]
[0.25999999 0.28       0.14      ]
[0.25999999 0.28       0.14      ]
[ 0.38        0.33000001 -0.05      ]
[ 0.38        0.33000001 -0.05      ]
[ 0.38        0.33000001 -0.05      ]
[0.13       0.13       0.25999999]
[0.13       0.13       0.25999999]
[ 0.57999998  0.15000001 -0.1       ]
[ 0.57999998  0.15000001 -0.1       ]
[ 0.57999998  0.15000001 -0.1       ]
[ 0.2         0.28999999 -0.09      ]
[ 0.2         0.28999999 -0.09      ]
[-0.05        0.41999999  0.15000001]
[-0.05        0.41999999  0.15000001]
[-0.05        0.41999999  0.15000001]
[ 0.12        0.25999999 -0.05      ]
[ 0.12        0.25999999 -0.05      ]
[-0.38999999  0.34        0.09      ]
[-0.38999999  0.34        0.09      ]
[ 0.16      

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-0.07        0.68000001  0.28999999]
[-0.07        0.68000001  0.28999999]
[0.27000001 0.38       0.19      ]
[0.27000001 0.38       0.19      ]
[0.02 0.11 0.07]
[0.02 0.11 0.07]
[0.02 0.11 0.07]
[-0.08 -0.08  0.07]
[-0.08 -0.08  0.07]
[ 0.01  0.08 -0.09]
[ 0.01  0.08 -0.09]
[ 0.01  0.08 -0.09]
[-0.20999999  0.28        0.17      ]
[-0.20999999  0.28        0.17      ]
[0.33000001 0.28999999 0.15000001]
[0.33000001 0.28999999 0.15000001]
[0.56       0.23999999 0.03      ]
[0.56       0.23999999 0.03      ]
[0.56       0.23999999 0.03      ]
[-0.27000001  0.13        0.19      ]
[-0.27000001  0.13        0.19      ]
[-0.27000001  0.13        0.19      ]
[0.31 0.06 0.11]
[0.31 0.06 0.11]
[ 0.44 -0.05 -0.03]
[ 0.44 -0.05 -0.03]
[0.16 0.11 0.25]
[0.16 0.11 0.25]
[0.16 0.11 0.25]
[-0.25        0.38        0.27000001]
[-0.25        0.38        0.27000001]
[-0.25        0.38        0.27000001]
[ 0.15000001  0.03       -0.02      ]
[ 0.15000001  0.03       -0.02      ]
[0.13       0.2        

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-0.18000001 -0.04        0.09      ]
[-0.18000001 -0.04        0.09      ]
[-0.18000001 -0.04        0.09      ]
[0.23       0.47       0.27000001]
[0.23       0.47       0.27000001]
[ 0.41999999  0.72000003 -0.07      ]
[ 0.41999999  0.72000003 -0.07      ]
[-0.11       -0.44999999 -0.11      ]
[-0.11       -0.44999999 -0.11      ]
[-0.11       -0.44999999 -0.11      ]
[-0.36000001  0.03        0.09      ]
[-0.36000001  0.03        0.09      ]
[-0.36000001  0.03        0.09      ]
[ 0.76999998  0.20999999 -0.01      ]
[ 0.76999998  0.20999999 -0.01      ]
[ 0.43000001  0.34       -0.03      ]
[ 0.43000001  0.34       -0.03      ]
[ 0.43000001  0.34       -0.03      ]
[-0.30000001  0.08        0.09      ]
[-0.30000001  0.08        0.09      ]
[-0.    0.04  0.11]
[ 0.06  0.05 -0.02]
[ 0.06  0.05 -0.02]
[ 0.06  0.05 -0.02]
[0.09 0.03 0.02]
[0.09 0.03 0.02]
[-0.08  0.07  0.07]
[-0.08  0.07  0.07]
[-0.08  0.07  0.07]
[-0.12  0.1   0.01]
[-0.12  0.1   0.01]
[-0.28999999  0.30000001  0.06  

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[0.09       0.25999999 0.12      ]
[0.09       0.25999999 0.12      ]
[0.09       0.25999999 0.12      ]
[0.68000001 0.67000002 0.31      ]
[0.68000001 0.67000002 0.31      ]
[0.68000001 0.67000002 0.31      ]
[0.16       0.30000001 0.11      ]
[0.16       0.30000001 0.11      ]
[ 0.22 -0.03 -0.08]
[ 0.22 -0.03 -0.08]
[ 0.22 -0.03 -0.08]
[ 0.2   0.09 -0.17]
[ 0.2   0.09 -0.17]
[-0.01  0.11 -0.06]
[-0.01  0.11 -0.06]
[-0.01  0.11 -0.06]
[-0.23999999  0.1        -0.05      ]
[-0.23999999  0.1        -0.05      ]
[-0.27000001  0.23999999  0.2       ]
[-0.27000001  0.23999999  0.2       ]
[-0.27000001  0.23999999  0.2       ]
[1.19000006 0.2        0.03      ]
[ 0.03 -0.04  0.14]
[ 0.03 -0.04  0.14]
[ 0.03 -0.04  0.14]
[ 0.07 -0.09  0.17]
[ 0.07 -0.09  0.17]
[ 0.13 -0.02 -0.05]
[ 0.13 -0.02 -0.05]
[ 0.04        0.28       -0.18000001]
[ 0.04        0.28       -0.18000001]
[ 0.04        0.28       -0.18000001]
[ 0.08        0.19       -0.23999999]
[ 0.08        0.19       -0.23999999]
[ 0.0

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[ 0.12       -0.1        -0.18000001]
[ 0.12       -0.1        -0.18000001]
[ 0.22 -0.   -0.1 ]
[ 0.22 -0.   -0.1 ]
[ 0.22 -0.   -0.1 ]
[0.19 0.1  0.19]
[0.19 0.1  0.19]
[0.23       0.18000001 0.15000001]
[0.23       0.18000001 0.15000001]
[0.23       0.18000001 0.15000001]
[ 0.50999999  0.07       -0.12      ]
[ 0.50999999  0.07       -0.12      ]
[-0.03        0.58999997  0.07      ]
[-0.03        0.58999997  0.07      ]
[-0.03        0.58999997  0.07      ]
[-0.14        0.40000001  0.19      ]
[-0.14        0.40000001  0.19      ]
[ 0.50999999 -0.01        0.03      ]
[ 0.50999999 -0.01        0.03      ]
[ 0.50999999 -0.01        0.03      ]
[ 0.12        0.15000001 -0.13      ]
[ 0.12        0.15000001 -0.13      ]
[ 0.02  0.04 -0.1 ]
[ 0.02  0.04 -0.1 ]
[ 0.02  0.04 -0.1 ]
[0.1  0.17 0.2 ]
[0.1  0.17 0.2 ]
[0.50999999 0.64999998 0.12      ]
[0.50999999 0.64999998 0.12      ]
[0.50999999 0.64999998 0.12      ]
[0.47       0.50999999 0.05      ]
[0.47       0.50999999 0.05      ]


/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[0.03 0.22 0.22]
[0.03 0.22 0.22]
[-0.03  0.47 -0.12]
[-0.03  0.47 -0.12]
[0.01       0.67000002 0.12      ]
[0.01       0.67000002 0.12      ]
[0.01       0.67000002 0.12      ]
[-0.03        0.25999999  0.17      ]
[-0.03        0.25999999  0.17      ]
[-0.03        0.25999999  0.17      ]
[0.34       0.27000001 0.2       ]
[0.34       0.27000001 0.2       ]
[ 0.03        0.72000003 -0.12      ]
[ 0.03        0.72000003 -0.12      ]
[ 0.03        0.72000003 -0.12      ]
[0.14 0.28 0.16]
[0.14 0.28 0.16]
[-0.16        0.23999999  0.14      ]
[-0.16        0.23999999  0.14      ]
[-0.16        0.23999999  0.14      ]
[ 0.07        0.49000001 -0.05      ]
[ 0.07        0.49000001 -0.05      ]
[ 0.41  0.03 -0.1 ]
[ 0.41  0.03 -0.1 ]
[ 0.41  0.03 -0.1 ]
[0.15000001 0.05       0.28      ]
[0.15000001 0.05       0.28      ]
[0.20999999 0.34       0.15000001]
[0.20999999 0.34       0.15000001]
[0.20999999 0.34       0.15000001]
[0.55000001 0.28       0.02      ]
[0.55000001 0.28       0.02  

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[ 0.12 -0.13 -0.28]
[ 0.40000001  0.36000001 -0.05      ]
[ 0.40000001  0.36000001 -0.05      ]
[ 0.40000001  0.36000001 -0.05      ]
[0.18000001 0.43000001 0.19      ]
[0.18000001 0.43000001 0.19      ]
[ 0.46000001  0.33000001 -0.34      ]
[ 0.46000001  0.33000001 -0.34      ]
[ 0.46000001  0.33000001 -0.34      ]
[ 0.11       -0.56       -0.31999999]
[ 0.11       -0.56       -0.31999999]
[-0.16  0.02 -0.02]
[-0.12        0.18000001  0.19      ]
[-0.12        0.18000001  0.19      ]
[ 0.03  0.05 -0.03]
[ 0.03  0.05 -0.03]
[ 0.03  0.05 -0.03]
[0.31999999 0.17       0.14      ]
[0.31999999 0.17       0.14      ]
[0.31999999 0.17       0.14      ]
[ 0.11        0.05       -0.36000001]
[ 0.11        0.05       -0.36000001]
[0.23       0.18000001 0.1       ]
[0.23       0.18000001 0.1       ]
[0.34 0.16 0.01]
[0.34 0.16 0.01]
[ 0.2  -0.06 -0.  ]
[ 0.2  -0.06 -0.  ]
[ 0.2  -0.06 -0.  ]
[-0.11  0.37  0.08]
[-0.11  0.37  0.08]
[-0.11  0.37  0.08]
[0.36000001 0.31999999 0.17      ]
[0.3600000

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[ 0.13 -0.   -0.13]
[ 0.13 -0.   -0.13]
[-0.30000001  0.17       -0.07      ]
[-0.30000001  0.17       -0.07      ]
[ 0.52999997  0.2        -0.16      ]
[ 0.52999997  0.2        -0.16      ]
[ 0.18000001  0.31       -0.04      ]
[ 0.18000001  0.31       -0.04      ]
[ 0.18000001  0.31       -0.04      ]
[-0.20999999  0.12        0.06      ]
[-0.20999999  0.12        0.06      ]
[-0.20999999  0.12        0.06      ]
[ 0.18000001  0.14       -0.14      ]
[ 0.18000001  0.14       -0.14      ]
[ 0.09  0.07 -0.  ]
[ 0.09  0.07 -0.  ]
[ 0.09  0.07 -0.  ]
[ 0.15000001 -0.20999999 -0.22      ]
[ 0.15000001 -0.20999999 -0.22      ]
[ 0.18000001 -0.73000002 -0.55000001]
[ 0.18000001 -0.73000002 -0.55000001]
[0.40000001 0.56       0.11      ]
[0.40000001 0.56       0.11      ]
[0.40000001 0.56       0.11      ]
[-0.37 -0.    0.01]
[-0.37 -0.    0.01]
[-0.37 -0.    0.01]
[-0.28999999 -0.09        0.13      ]
[-0.28999999 -0.09        0.13      ]
[-0.69 -0.11 -0.07]
[ 0.38999999 -0.2        -0.23 

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-0.16  0.13  0.22]
[-0.16  0.13  0.22]
[0.58999997 0.28999999 0.03      ]
[0.58999997 0.28999999 0.03      ]
[0.58999997 0.28999999 0.03      ]
[0.54000002 0.34       0.12      ]
[0.54000002 0.34       0.12      ]
[0.25999999 0.18000001 0.20999999]
[0.25999999 0.18000001 0.20999999]
[0.25999999 0.18000001 0.20999999]
[0.13 0.37 0.04]
[0.13 0.37 0.04]
[0.25       0.01       0.27000001]
[0.25       0.01       0.27000001]
[0.25       0.01       0.27000001]
[-0.01  0.02  0.04]
[-0.01  0.02  0.04]
[-0.06  0.08 -0.08]
[-0.06  0.08 -0.08]
[-0.06  0.08 -0.08]
[0.23999999 0.25       0.03      ]
[0.23999999 0.25       0.03      ]
[ 0.38999999  0.38       -0.1       ]
[ 0.38999999  0.38       -0.1       ]
[ 0.38999999  0.38       -0.1       ]
[ 0.56999999 -0.07        0.02      ]
[ 0.56999999 -0.07        0.02      ]
[-0.61000001  0.14       -0.11      ]
[-0.61000001  0.14       -0.11      ]
[-0.61000001  0.14       -0.11      ]
[-0.56 -0.13  0.01]
[-0.56 -0.13  0.01]
[0.31       0.30000001 0.17

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-0.15000001  0.11       -0.23999999]
[-0.28  0.23  0.31]
[-0.28  0.23  0.31]
[-0.28  0.23  0.31]
[0.09       0.15000001 0.16      ]
[0.09       0.15000001 0.16      ]
[0.38       0.46000001 0.14      ]
[0.38       0.46000001 0.14      ]
[0.38       0.46000001 0.14      ]
[ 0.40000001  0.13       -0.30000001]
[ 0.40000001  0.13       -0.30000001]
[ 0.40000001  0.13       -0.30000001]
[ 0.01        0.20999999 -0.04      ]
[ 0.01        0.20999999 -0.04      ]
[ 0.15000001  0.01       -0.02      ]
[ 0.15000001  0.01       -0.02      ]
[ 0.15000001  0.01       -0.02      ]
[0.12       0.30000001 0.01      ]
[0.12       0.30000001 0.01      ]
[0.41 0.17 0.07]
[0.41 0.17 0.07]
[0.41 0.17 0.07]
[-0.1   0.09 -0.06]
[-0.1   0.09 -0.06]
[-0.52999997  0.40000001  0.09      ]
[-0.52999997  0.40000001  0.09      ]
[-0.52999997  0.40000001  0.09      ]
[-0.44999999 -0.06       -0.05      ]
[-0.44999999 -0.06       -0.05      ]
[-0.63  0.05  0.13]
[-0.63  0.05  0.13]
[-0.63  0.05  0.13]
[-0.18000001

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[ 0.61000001 -0.36000001 -0.46000001]
[ 0.61000001 -0.36000001 -0.46000001]
[ 0.61000001 -0.36000001 -0.46000001]
[-0.47999999  0.19        0.15000001]
[-0.47999999  0.19        0.15000001]
[ 0.02        0.40000001 -0.08      ]
[ 0.02        0.40000001 -0.08      ]
[ 0.02        0.40000001 -0.08      ]
[ 0.52999997  0.25999999 -0.15000001]
[ 0.52999997  0.25999999 -0.15000001]
[-0.02  0.22 -0.02]
[-0.02  0.22 -0.02]
[0.1  0.22 0.02]
[0.1  0.22 0.02]
[0.1  0.22 0.02]
[ 0.28        0.13       -0.15000001]
[ 0.28        0.13       -0.15000001]
[-0.    0.25  0.04]
[-0.    0.25  0.04]
[-0.    0.25  0.04]
[ 0.09  0.25 -0.05]
[ 0.09  0.25 -0.05]
[ 0.09  0.25 -0.05]
[ 0.13 -0.25 -0.23]
[ 0.13 -0.25 -0.23]
[-0.43000001  0.20999999  0.04      ]
[-0.11        0.04       -0.20999999]
[-0.11        0.04       -0.20999999]
[-0.11        0.04       -0.20999999]
[ 0.57999998  0.25       -0.1       ]
[ 0.57999998  0.25       -0.1       ]
[0.31999999 0.28999999 0.2       ]
[0.31999999 0.28999999 0.2    

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-0.16       -0.40000001 -0.03      ]
[0.23999999 0.37       0.14      ]
[0.23999999 0.37       0.14      ]
[0.14 0.19 0.07]
[0.14 0.19 0.07]
[0.14 0.19 0.07]
[ 0.41        0.23       -0.27000001]
[ 0.41        0.23       -0.27000001]
[ 0.62        0.46000001 -0.23999999]
[ 0.62        0.46000001 -0.23999999]
[ 0.62        0.46000001 -0.23999999]
[ 0.01  0.01 -0.16]
[ 0.01  0.01 -0.16]
[0.11       0.38999999 0.15000001]
[0.11       0.38999999 0.15000001]
[0.11       0.38999999 0.15000001]
[ 0.30000001  0.03       -0.02      ]
[ 0.30000001  0.03       -0.02      ]
[0.14 0.14 0.09]
[0.14 0.14 0.09]
[0.14 0.14 0.09]
[0.05       0.50999999 0.08      ]
[0.05       0.50999999 0.08      ]
[-0.19  0.03 -0.08]
[-0.19  0.03 -0.08]
[-0.19  0.03 -0.08]
[-0.09 -0.01 -0.05]
[-0.09 -0.01 -0.05]
[ 0.82999998  0.46000001 -0.1       ]
[ 0.82999998  0.46000001 -0.1       ]
[ 0.82999998  0.46000001 -0.1       ]
[-0.12  0.14 -0.06]
[-0.12  0.14 -0.06]
[-0.12  0.14 -0.06]
[-0.02 -0.03  0.25]
[-0.02 -0.03  0

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-0.25 -0.13 -0.13]
[-0.25 -0.13 -0.13]
[-0.25 -0.13 -0.13]
[-0.16        0.02        0.18000001]
[-0.16        0.02        0.18000001]
[ 0.23       -0.52999997 -0.25999999]
[ 0.23       -0.52999997 -0.25999999]
[ 0.23       -0.52999997 -0.25999999]
[0.28       0.41999999 0.05      ]
[0.28       0.41999999 0.05      ]
[-0.01  0.41  0.31]
[-0.01  0.41  0.31]
[-0.01  0.41  0.31]
[ 0.34 -0.1   0.03]
[ 0.34 -0.1   0.03]
[-0.23999999  0.12       -0.05      ]
[-0.23999999  0.12       -0.05      ]
[-0.23999999  0.12       -0.05      ]
[-0.34 -0.19  0.17]
[-0.34 -0.19  0.17]
[-0.23 -0.63  0.09]
[-0.23 -0.63  0.09]
[-0.23 -0.63  0.09]
[-0.58999997 -0.97000003  0.11      ]
[-0.58999997 -0.97000003  0.11      ]
[-0.54000002 -1.05999994  0.57999998]
[-1.01999998 -1.94000006  1.02999997]
[-1.01999998 -1.94000006  1.02999997]
[-1.46000004 -3.80999994  1.30999994]
[-1.46000004 -3.80999994  1.30999994]
[-1.46000004 -3.80999994  1.30999994]
[-1.87       -3.8599999   1.50999999]
[-1.87       -3.8599999 

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[ -7.75       -33.98999786  13.59000015]
[ -7.71999979 -35.18000031  14.56999969]
[ -7.71999979 -35.18000031  14.56999969]
[ -7.71999979 -35.18000031  14.56999969]
[ -8.68000031 -40.23000336  16.87999916]
[ -8.68000031 -40.23000336  16.87999916]
[ -9.97999954 -44.79000092  15.59000015]
[ -9.97999954 -44.79000092  15.59000015]
[ -9.97999954 -44.79000092  15.59000015]
[ -7.98000002 -46.58999634  17.84000015]
[ -7.98000002 -46.58999634  17.84000015]
[ -7.05000019 -47.62999725  20.87999916]
[ -7.05000019 -47.62999725  20.87999916]
[ -7.05000019 -47.62999725  20.87999916]
[ -7.23999977 -49.54000092  23.96999931]
[ -7.23999977 -49.54000092  23.96999931]
[ -8.97000027 -55.84999847  25.35000038]
[ -8.97000027 -55.84999847  25.35000038]
[ -8.97000027 -55.84999847  25.35000038]
[ -9.90999985 -57.93000031  25.94999886]
[-14.15999985 -65.31999969  31.27999878]
[-14.15999985 -65.31999969  31.27999878]
[-14.42000008 -68.80000305  33.18999863]
[-14.42000008 -68.80000305  33.18999863]
[-14.42000008 -6

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[ -21.98000145 -106.09999847   76.03000641]
[ -21.98000145 -106.09999847   76.03000641]
[ -21.98000145 -106.09999847   76.03000641]
[ -21.90000153 -105.95999908   76.53000641]
[ -21.90000153 -105.95999908   76.53000641]
[ -20.80000114 -104.45999908   79.08000183]
[ -20.80000114 -104.45999908   79.08000183]
[ -20.42000008 -104.88000488   79.62000275]
[ -20.42000008 -104.88000488   79.62000275]
[ -20.42000008 -104.88000488   79.62000275]
[ -19.73999977 -104.38999939   82.23000336]
[ -19.73999977 -104.38999939   82.23000336]
[ -19.73999977 -104.38999939   82.23000336]
[ -19.23000145 -104.52999878   85.01000214]
[ -19.23000145 -104.52999878   85.01000214]
[ -17.96999931 -102.34000397   87.18000031]
[ -17.96999931 -102.34000397   87.18000031]
[-20.13000107 -97.01000214  94.36000061]
[-20.13000107 -97.01000214  94.36000061]
[-20.48999977 -95.59000397  93.88000488]
[-20.48999977 -95.59000397  93.88000488]
[-20.48999977 -95.59000397  93.88000488]
[-20.28000069 -94.43000031  91.97000122]
[-20.2

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[-19.42000008 -95.59999847 117.9200058 ]
[-19.42000008 -95.59999847 117.9200058 ]
[-19.42000008 -95.59999847 117.9200058 ]
[-19.13000107 -93.65000153 119.13000488]
[-19.13000107 -93.65000153 119.13000488]
[-18.20000076 -92.06999969 120.6000061 ]
[-18.20000076 -92.06999969 120.6000061 ]
[-18.20000076 -92.06999969 120.6000061 ]
[-16.80000114 -89.98000336 124.47000122]
[-16.80000114 -89.98000336 124.47000122]
[-18.63000107 -90.19000244 124.63000488]
[-18.63000107 -90.19000244 124.63000488]
[-18.63000107 -90.19000244 124.63000488]
[-19.8200016  -90.37000275 124.8500061 ]
[-19.8200016  -90.37000275 124.8500061 ]
[-20.8900013  -87.83000183 127.55000305]
[-20.8900013  -87.83000183 127.55000305]
[-20.8900013  -87.83000183 127.55000305]
[-20.93000031 -86.59999847 128.91999817]
[-20.93000031 -86.59999847 128.91999817]
[-21.57999992 -86.09000397 129.19000244]
[-21.57999992 -86.09000397 129.19000244]
[-21.57999992 -86.09000397 129.19000244]
[-21.04000092 -85.70999908 129.17999268]
[-21.04000092 -8

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[13.58000088 -4.75       62.43999863]
[13.58000088 -4.75       62.43999863]
[14.19999981 -4.92999983 63.56000137]
[14.19999981 -4.92999983 63.56000137]
[18.77999878  4.78000021 58.70000076]
[18.77999878  4.78000021 58.70000076]
[18.77999878  4.78000021 58.70000076]
[17.84000015  6.86999989 60.63000107]
[17.84000015  6.86999989 60.63000107]
[17.20999908  2.46000004 61.04000092]
[17.20999908  2.46000004 61.04000092]
[17.20999908  2.46000004 61.04000092]
[17.12999916  5.48999977 58.09000015]
[17.12999916  5.48999977 58.09000015]
[16.34000015  3.69000101 61.        ]
[16.34000015  3.69000101 61.        ]
[16.34000015  3.69000101 61.        ]
[17.59999847  2.99000001 59.89999771]
[17.59999847  2.99000001 59.89999771]
[14.76000118  2.3499999  61.31000137]
[14.76000118  2.3499999  61.31000137]
[14.76000118  2.3499999  61.31000137]
[18.01999855  4.96000004 57.20000076]
[18.01999855  4.96000004 57.20000076]
[17.89999962  3.67000008 58.68000031]
[17.89999962  3.67000008 58.68000031]
[17.89999962

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[17.77999878  2.73000002 58.06999969]
[17.51999855  1.24000001 61.59000015]
[17.51999855  1.24000001 61.59000015]
[17.70999908  4.86000013 57.43999863]
[17.70999908  4.86000013 57.43999863]
[18.19999886  5.78000021 56.36999893]
[18.19999886  5.78000021 56.36999893]
[16.22999954  2.00999999 59.59000015]
[16.22999954  2.00999999 59.59000015]
[16.22999954  2.00999999 59.59000015]
[17.80999947  2.91000009 58.79999924]
[17.80999947  2.91000009 58.79999924]
[17.75        5.38000011 56.77000046]
[17.75        5.38000011 56.77000046]
[17.75        5.38000011 56.77000046]
[16.87999916  0.51999998 61.93999863]
[16.87999916  0.51999998 61.93999863]
[17.82999992  3.5999999  57.09999847]
[17.82999992  3.5999999  57.09999847]
[17.82999992  3.5999999  57.09999847]
[17.51000023  4.11000013 56.73999786]
[17.51000023  4.11000013 56.73999786]
[16.38999939  3.42000008 58.27000046]
[16.38999939  3.42000008 58.27000046]
[16.38999939  3.42000008 58.27000046]
[16.82999992  2.36999989 57.61000061]
[16.82999992

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[16.80999947  2.66000009 56.93999863]
[16.80999947  2.66000009 56.93999863]
[16.80999947  2.66000009 56.93999863]
[16.25        1.79999995 58.79999924]
[16.25        1.79999995 58.79999924]
[16.47999954  3.11999989 56.68999863]
[16.47999954  3.11999989 56.68999863]
[16.47999954  3.11999989 56.68999863]
[16.09000015  2.8900001  56.70000076]
[16.09000015  2.8900001  56.70000076]
[17.34999847  1.40999997 60.52999878]
[17.34999847  1.40999997 60.52999878]
[17.34999847  1.40999997 60.52999878]
[16.14999962  3.         56.43000031]
[16.14999962  3.         56.43000031]
[15.75000095  2.27999997 57.36999893]
[15.75000095  2.27999997 57.36999893]
[15.75000095  2.27999997 57.36999893]
[17.29999924  1.63999999 59.47999954]
[17.29999924  1.63999999 59.47999954]
[15.77999973  2.70000005 56.61999893]
[15.77999973  2.70000005 56.61999893]
[15.77999973  2.70000005 56.61999893]
[17.30999947 -0.18000001 62.18000031]
[17.30999947 -0.18000001 62.18000031]
[16.53999901  2.9000001  56.61000061]
[16.53999901

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[17.92000008 -0.44999999 62.27999878]
[17.92000008 -0.44999999 62.27999878]
[15.83000088  1.97000003 56.81999969]
[15.83000088  1.97000003 56.81999969]
[17.18999863 -0.60000002 62.02000046]
[17.18999863 -0.60000002 62.02000046]
[17.18999863 -0.60000002 62.02000046]
[16.70999908  1.51999998 58.20000076]
[16.70999908  1.51999998 58.20000076]
[17.14999962 -0.1        61.18000031]
[17.14999962 -0.1        61.18000031]
[17.14999962 -0.1        61.18000031]
[17.31999969 -0.34       62.04000092]
[17.31999969 -0.34       62.04000092]
[15.78999996  2.19000101 56.91999817]
[15.78999996  2.19000101 56.91999817]
[15.78999996  2.19000101 56.91999817]
[17.23999977 -0.56       61.31999969]
[17.23999977 -0.56       61.31999969]
[17.9299984  -0.68000001 62.22999954]
[17.9299984  -0.68000001 62.22999954]
[17.9299984  -0.68000001 62.22999954]
[16.69999886  1.04999995 58.59999847]
[16.69999886  1.04999995 58.59999847]
[17.1099987  -0.47999999 61.70999908]
[17.1099987  -0.47999999 61.70999908]
[17.1099987 

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[17.1099987 -0.5       61.25     ]
[16.98999977 -0.56999999 61.13999939]
[16.98999977 -0.56999999 61.13999939]
[16.98999977 -0.56999999 61.13999939]
[17.17000008 -0.67000002 61.36999893]
[17.17000008 -0.67000002 61.36999893]
[16.88999939 -0.52999997 61.50999832]
[16.88999939 -0.52999997 61.50999832]
[16.88999939 -0.52999997 61.50999832]
[17.30999947 -0.58999997 61.32999802]
[17.30999947 -0.58999997 61.32999802]
[17.02999878 -0.54000002 61.57999802]
[17.02999878 -0.54000002 61.57999802]
[17.02999878 -0.54000002 61.57999802]
[16.62999916 -0.49000001 61.09000015]
[16.62999916 -0.49000001 61.09000015]
[17.14999962 -0.46000001 61.56999969]
[17.14999962 -0.46000001 61.56999969]
[17.14999962 -0.46000001 61.56999969]
[16.56999969 -0.47       61.13000107]
[16.56999969 -0.47       61.13000107]
[16.72999954 -0.54000002 60.89999771]
[16.72999954 -0.54000002 60.89999771]
[16.72999954 -0.54000002 60.89999771]
[17.1099987  -0.49000001 61.56999969]
[17.1099987  -0.49000001 61.56999969]
[16.69999886 -0

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[16.42000008 -0.49000001 60.38000107]
[16.42000008 -0.49000001 60.38000107]
[16.42000008 -0.49000001 60.38000107]
[16.56999969 -0.41999999 60.43000031]
[16.56999969 -0.41999999 60.43000031]
[16.56999969 -0.41999999 60.43000031]
[16.77999878 -0.56999999 61.09000015]
[16.77999878 -0.56999999 61.09000015]
[16.29999924 -0.23       60.48999786]
[16.29999924 -0.23       60.48999786]
[16.29999924 -0.23       60.48999786]
[16.43999863 -0.41999999 60.38000107]
[16.43999863 -0.41999999 60.38000107]
[16.62999916 -0.70999998 61.09000015]
[16.62999916 -0.70999998 61.09000015]
[16.23999977 -0.08       60.29999924]
[16.23999977 -0.08       60.29999924]
[16.54999924 -0.36000001 60.75      ]
[16.54999924 -0.36000001 60.75      ]
[16.26000023 -0.22       60.43999863]
[16.26000023 -0.22       60.43999863]
[16.26000023 -0.22       60.43999863]
[16.26000023 -0.22       60.43999863]
[16.29999924 -0.44999999 60.48999786]
[16.29999924 -0.44999999 60.48999786]
[16.40999985 -0.44999999 60.56999969]
[16.40999985

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[16.18999863 -0.30000001 60.13000107]
[16.18999863 -0.30000001 60.13000107]
[16.07999992 -0.28       59.93000031]
[16.07999992 -0.28       59.93000031]
[16.01000023 -0.09       60.18000031]
[16.01000023 -0.09       60.18000031]
[16.01000023 -0.09       60.18000031]
[15.92000103 -0.28999999 59.95999908]
[15.92000103 -0.28999999 59.95999908]
[16.21999931 -0.15000001 60.04999924]
[16.21999931 -0.15000001 60.04999924]
[16.21999931 -0.15000001 60.04999924]
[15.93999958 -0.18000001 59.84999847]
[15.93999958 -0.18000001 59.84999847]
[15.97999954 -0.17       59.90999985]
[15.97999954 -0.17       59.90999985]
[15.97999954 -0.17       59.90999985]
[16.09999847 -0.22       59.81999969]
[16.09999847 -0.22       59.81999969]
[15.97999954 -0.22       59.75999832]
[15.97999954 -0.22       59.75999832]
[15.97999954 -0.22       59.75999832]
[16.09999847 -0.12       59.86999893]
[16.09999847 -0.12       59.86999893]
[15.90000057 -0.23       59.81000137]
[15.90000057 -0.23       59.81000137]
[15.90000057

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[ 1.56999998e+01 -1.99999996e-02  5.91199989e+01]
[ 1.56999998e+01 -1.99999996e-02  5.91199989e+01]
[ 1.56999998e+01 -1.99999996e-02  5.91199989e+01]
[15.60999966 -0.08       59.52999878]
[15.60999966 -0.08       59.52999878]
[15.90000057 -0.28       59.68000031]
[15.90000057 -0.28       59.68000031]
[15.90000057 -0.28       59.68000031]
[15.49000072 -0.11       59.18999863]
[15.49000072 -0.11       59.18999863]
[15.51000118  0.1        59.27999878]
[15.51000118  0.1        59.27999878]
[15.51000118  0.1        59.27999878]
[ 1.57200003e+01 -2.99999993e-02  5.93999977e+01]
[ 1.57200003e+01 -2.99999993e-02  5.93999977e+01]
[15.52999973 -0.08       59.23999786]
[15.52999973 -0.08       59.23999786]
[15.52999973 -0.08       59.23999786]
[15.42999935 -0.22       59.09000015]
[15.42999935 -0.22       59.09000015]
[15.51000118 -0.17       59.15999985]
[15.51000118 -0.17       59.15999985]
[15.51000118 -0.17       59.15999985]
[15.53999996 -0.18000001 59.15999985]
[15.53999996 -0.18000001 59.

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[15.18999958 -0.09       58.89999771]
[15.18999958 -0.09       58.89999771]
[15.18999958 -0.09       58.89999771]
[15.43999958 -0.06       58.93000031]
[15.43999958 -0.06       58.93000031]
[15.43999958 -0.06       58.93000031]
[1.53699999e+01 5.00000007e-02 5.88299980e+01]
[1.53699999e+01 5.00000007e-02 5.88299980e+01]
[15.46000004 -0.07       58.79000092]
[15.46000004 -0.07       58.79000092]
[15.31000042 -0.         58.89999771]
[15.31000042 -0.         58.89999771]
[15.31000042 -0.         58.89999771]
[15.27999973 -0.         58.70000076]
[15.27999973 -0.         58.70000076]
[15.24000072  0.19       58.86999893]
[15.24000072  0.19       58.86999893]
[1.53900003e+01 9.99999978e-03 5.88800011e+01]
[1.53900003e+01 9.99999978e-03 5.88800011e+01]
[1.53900003e+01 9.99999978e-03 5.88800011e+01]
[15.27999973  0.06       58.82999802]
[15.27999973  0.06       58.82999802]
[15.27999973  0.06       58.82999802]
[15.28999996 -0.1        58.73999786]
[15.28999996 -0.1        58.73999786]
[15.2

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[15.07000065  0.06       58.38999939]
[15.07000065  0.06       58.38999939]
[15.07000065  0.06       58.38999939]
[1.50900011e+01 1.99999996e-02 5.83600006e+01]
[1.50900011e+01 1.99999996e-02 5.83600006e+01]
[1.50900011e+01 1.99999996e-02 5.83600006e+01]
[14.99000072  0.06       58.47000122]
[14.99000072  0.06       58.47000122]
[15.03999996  0.11       58.22000122]
[15.03999996  0.11       58.22000122]
[1.49900007e+01 1.99999996e-02 5.82299995e+01]
[1.49900007e+01 1.99999996e-02 5.82299995e+01]
[15.02000046  0.1        58.15999985]
[15.02000046  0.1        58.15999985]
[15.02000046  0.1        58.15999985]
[15.02000046  0.1        58.15999985]
[1.49200010e+01 5.00000007e-02 5.83800011e+01]
[1.49200010e+01 5.00000007e-02 5.83800011e+01]
[1.48900003e+01 1.99999996e-02 5.82200012e+01]
[1.48900003e+01 1.99999996e-02 5.82200012e+01]
[1.48900003e+01 1.99999996e-02 5.82200012e+01]
[1.50100012e+01 5.00000007e-02 5.83499985e+01]
[1.50100012e+01 5.00000007e-02 5.83499985e+01]
[14.94999981  0.11

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[14.80000019 -0.         58.02999878]
[14.72000027  0.15000001 58.11000061]
[14.72000027  0.15000001 58.11000061]
[14.78999996  0.07       58.02999878]
[14.78999996  0.07       58.02999878]
[14.78999996  0.07       58.02999878]
[1.47299995e+01 3.99999991e-02 5.80099983e+01]
[1.47299995e+01 3.99999991e-02 5.80099983e+01]
[15.02000046  0.09       58.07999802]
[15.02000046  0.09       58.07999802]
[15.02000046  0.09       58.07999802]
[14.71000004  0.1        58.25999832]
[14.71000004  0.1        58.25999832]
[14.81000042  0.16       58.06000137]
[14.81000042  0.16       58.06000137]
[14.81000042  0.16       58.06000137]
[14.94999981  0.19       57.95999908]
[14.94999981  0.19       57.95999908]
[14.84000111  0.08       58.06999969]
[14.84000111  0.08       58.06999969]
[14.84000111  0.08       58.06999969]
[14.86999989  0.12       57.95000076]
[14.86999989  0.12       57.95000076]
[14.86999989  0.19       58.06000137]
[14.86999989  0.19       58.06000137]
[14.86999989  0.19       58.0600

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[1.46899996e+01 1.99999996e-02 5.78600006e+01]
[1.46899996e+01 1.99999996e-02 5.78600006e+01]
[1.46899996e+01 1.99999996e-02 5.78600006e+01]
[14.68999958  0.12       57.77999878]
[14.68999958  0.12       57.77999878]
[14.74000072  0.09       57.65999985]
[14.74000072  0.09       57.65999985]
[14.74000072  0.09       57.65999985]
[14.72999954  0.11       57.88999939]
[14.72999954  0.11       57.88999939]
[14.61999989  0.13       57.70000076]
[14.61999989  0.13       57.70000076]
[14.61999989  0.13       57.70000076]
[1.47200003e+01 5.00000007e-02 5.76599998e+01]
[1.47200003e+01 5.00000007e-02 5.76599998e+01]
[14.68999958  0.08       57.66999817]
[14.68999958  0.08       57.66999817]
[14.68999958  0.08       57.66999817]
[14.89000034  0.15000001 57.77000046]
[14.89000034  0.15000001 57.77000046]
[14.69999981  0.12       57.79000092]
[14.69999981  0.12       57.79000092]
[14.69999981  0.12       57.79000092]
[1.46600008e+01 3.99999991e-02 5.78100014e+01]
[1.46600008e+01 3.99999991e-02 5.7

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[14.64000034  0.17       57.54999924]
[14.52000046  0.1        57.52999878]
[14.52000046  0.1        57.52999878]
[14.52000046  0.1        57.59000015]
[14.52000046  0.1        57.59000015]
[14.52000046  0.1        57.59000015]
[ 1.45500002e+01 -3.99999991e-02  5.74399986e+01]
[ 1.45500002e+01 -3.99999991e-02  5.74399986e+01]
[14.47000027  0.11       57.31000137]
[14.47000027  0.11       57.31000137]
[14.47000027  0.11       57.31000137]
[14.51000118  0.12       57.56000137]
[14.51000118  0.12       57.56000137]
[14.51000118  0.12       57.56000137]
[14.47999954  0.06       57.48999786]
[14.47999954  0.06       57.48999786]
[14.34999943  0.11       57.36000061]
[14.34999943  0.11       57.36000061]
[14.24000072  0.17       57.31999969]
[14.24000072  0.17       57.31999969]
[14.24000072  0.17       57.31999969]
[14.63000011  0.11       57.68000031]
[14.63000011  0.11       57.68000031]
[1.45600004e+01 3.99999991e-02 5.71399994e+01]
[1.45600004e+01 3.99999991e-02 5.71399994e+01]
[1.45600

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[14.47999954  0.19       57.27000046]
[14.47999954  0.19       57.27000046]
[1.44000006e+01 3.99999991e-02 5.72500000e+01]
[1.44000006e+01 3.99999991e-02 5.72500000e+01]
[14.42000103  0.18000001 57.27999878]
[14.42000103  0.18000001 57.27999878]
[14.42000103  0.18000001 57.27999878]
[14.36999989  0.20999999 57.45000076]
[14.36999989  0.20999999 57.45000076]
[14.36999989  0.15000001 56.98999786]
[14.36999989  0.15000001 56.98999786]
[14.36999989  0.15000001 56.98999786]
[14.40000057  0.11       57.15999985]
[14.40000057  0.11       57.15999985]
[14.4100008   0.15000001 57.        ]
[14.4100008   0.15000001 57.        ]
[14.4100008   0.15000001 57.        ]
[14.24000072  0.22       57.06000137]
[14.24000072  0.22       57.06000137]
[14.22000027  0.12       57.07999802]
[14.22000027  0.12       57.07999802]
[14.22000027  0.12       57.07999802]
[14.49000072  0.16       57.25      ]
[14.49000072  0.16       57.25      ]
[14.34999943  0.08       57.16999817]
[14.34999943  0.08       57.1699

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[14.17000103  0.28       56.91999817]
[14.17000103  0.28       56.91999817]
[14.22000027  0.20999999 57.09000015]
[14.22000027  0.20999999 57.09000015]
[14.15000057  0.12       56.89999771]
[14.15000057  0.12       56.89999771]
[14.15000057  0.12       56.89999771]
[14.11999989  0.23       56.72000122]
[14.11999989  0.23       56.72000122]
[14.11999989  0.19       56.79000092]
[14.11999989  0.19       56.79000092]
[14.31000042  0.22       56.81000137]
[14.31000042  0.22       56.81000137]
[14.31000042  0.22       56.81000137]
[14.14000034  0.28999999 56.98999786]
[14.17000103  0.18000001 56.88999939]
[14.17000103  0.18000001 56.88999939]
[14.17000103  0.18000001 56.88999939]
[14.17000103  0.18000001 56.88999939]
[14.1600008   0.30000001 56.90999985]
[14.1600008   0.30000001 56.90999985]
[14.1600008   0.30000001 56.90999985]
[14.17000103  0.28       56.86000061]
[14.17000103  0.28       56.86000061]
[14.10999966  0.22       56.84000015]
[14.10999966  0.22       56.84000015]
[14.10999966

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[14.09000111  0.37       56.57999802]
[14.09000111  0.37       56.57999802]
[14.22999954  0.16       56.72999954]
[14.22999954  0.16       56.72999954]
[14.22999954  0.16       56.72999954]
[13.97999954  0.22       56.50999832]
[13.97999954  0.22       56.50999832]
[13.90000057  0.33000001 56.47000122]
[13.90000057  0.33000001 56.47000122]
[13.90000057  0.33000001 56.47000122]
[14.18999958  0.19       56.68999863]
[14.18999958  0.19       56.68999863]
[13.90000057  0.27000001 56.66999817]
[13.90000057  0.27000001 56.66999817]
[13.90000057  0.27000001 56.66999817]
[14.03999996  0.28       56.68000031]
[14.03999996  0.28       56.68000031]
[14.1600008   0.25       56.56999969]
[14.1600008   0.25       56.56999969]
[13.93999958  0.2        56.65999985]
[13.93999958  0.2        56.65999985]
[13.93999958  0.2        56.65999985]
[13.97999954  0.23       56.72999954]
[13.97999954  0.23       56.72999954]
[13.97999954  0.23       56.72999954]
[13.82000065  0.25       56.43000031]
[13.82000065

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[13.83000088  0.25999999 56.34999847]
[13.83000088  0.25999999 56.34999847]
[13.94999981  0.30000001 56.45999908]
[13.94999981  0.30000001 56.45999908]
[14.02000046  0.28999999 56.27000046]
[14.02000046  0.28999999 56.27000046]
[14.02000046  0.28999999 56.27000046]
[13.84999943  0.49000001 56.29999924]
[13.84999943  0.49000001 56.29999924]
[14.05000019  0.20999999 56.54000092]
[14.05000019  0.20999999 56.54000092]
[13.75000095  0.27000001 56.36999893]
[13.75000095  0.27000001 56.36999893]
[13.75000095  0.27000001 56.36999893]
[13.84999943  0.31999999 56.27999878]
[13.84999943  0.31999999 56.27999878]
[13.77999973  0.31999999 56.34999847]
[13.77999973  0.31999999 56.34999847]
[13.77999973  0.31999999 56.34999847]
[13.67999935  0.34       56.11000061]
[13.67999935  0.34       56.11000061]
[13.67999935  0.34       56.11000061]
[13.94999981  0.28       56.29000092]
[13.94999981  0.28       56.29000092]
[13.80000019  0.34999999 56.15999985]
[13.80000019  0.34999999 56.15999985]
[13.80000019

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[13.69999981  0.33000001 56.18999863]
[13.67999935  0.28999999 56.23999786]
[13.67999935  0.28999999 56.23999786]
[13.67999935  0.28999999 56.23999786]
[13.67999935  0.31999999 56.09000015]
[13.67999935  0.31999999 56.09000015]
[13.83000088  0.25999999 56.20999908]
[13.83000088  0.25999999 56.20999908]
[13.83000088  0.25999999 56.20999908]
[13.67000103  0.25999999 56.09999847]
[13.67000103  0.25999999 56.09999847]
[13.59999943  0.23       56.20000076]
[13.59999943  0.23       56.20000076]
[13.59999943  0.23       56.20000076]
[13.71000004  0.30000001 56.20000076]
[13.71000004  0.30000001 56.20000076]
[13.78999996  0.34       56.09000015]
[13.78999996  0.34       56.09000015]
[13.78999996  0.34       56.09000015]
[13.81000042  0.28       56.09999847]
[13.81000042  0.28       56.09999847]
[13.74000072  0.31999999 56.14999771]
[13.74000072  0.31999999 56.14999771]
[13.74000072  0.31999999 56.14999771]
[13.67999935  0.41       56.15999985]
[13.67999935  0.41       56.15999985]
[13.60999966

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[13.84000111  0.41       56.09000015]
[13.84000111  0.41       56.09000015]
[13.63000011  0.37       55.79000092]
[13.63000011  0.37       55.79000092]
[13.58000088  0.27000001 55.91999817]
[13.52000046  0.36000001 55.88999939]
[13.56000042  0.25       55.91999817]
[13.56000042  0.25       55.91999817]
[13.56000042  0.25       55.91999817]
[13.6600008   0.38999999 55.79999924]
[13.6600008   0.38999999 55.79999924]
[13.61999989  0.28999999 55.82999802]
[13.61999989  0.28999999 55.82999802]
[13.61999989  0.28999999 55.82999802]
[13.59000111  0.25999999 55.89999771]
[13.59000111  0.25999999 55.89999771]
[13.59000111  0.25999999 55.89999771]
[13.67999935  0.37       55.79000092]
[13.67999935  0.37       55.79000092]
[13.52000046  0.37       55.88999939]
[13.52000046  0.37       55.88999939]
[13.6600008   0.36000001 55.84999847]
[13.6600008   0.36000001 55.84999847]
[13.6600008   0.36000001 55.84999847]
[13.51000118  0.38999999 55.75999832]
[13.51000118  0.38999999 55.75999832]
[13.63000011

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[13.55000019  0.38999999 55.75999832]
[13.56000042  0.34       55.70000076]
[13.56000042  0.34       55.70000076]
[13.56000042  0.34       55.70000076]
[13.67000103  0.36000001 55.77000046]
[13.67000103  0.36000001 55.77000046]
[13.67000103  0.36000001 55.77000046]
[13.49000072  0.30000001 55.66999817]
[13.49000072  0.30000001 55.66999817]
[13.77999973  0.38       55.82999802]
[13.77999973  0.38       55.82999802]
[13.58000088  0.27000001 55.75999832]
[13.58000088  0.27000001 55.75999832]
[13.58000088  0.27000001 55.75999832]
[ 1.37500010e+01 -2.99999993e-02  5.59199982e+01]
[ 1.37500010e+01 -2.99999993e-02  5.59199982e+01]
[13.6600008   0.27000001 55.72000122]
[13.6600008   0.27000001 55.72000122]
[13.6600008   0.27000001 55.72000122]
[13.44999981  0.23       55.43999863]
[13.44999981  0.23       55.43999863]
[13.57000065  0.11       55.75999832]
[13.57000065  0.11       55.75999832]
[13.57000065  0.11       55.75999832]
[13.69999981  0.17       55.84999847]
[13.69999981  0.17       5

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[14.24000072  0.31       56.25999832]
[14.24000072  0.31       56.25999832]
[14.24000072  0.31       56.25999832]
[10.64000034  3.98000002 42.84000015]
[10.64000034  3.98000002 42.84000015]
[ 9.19000053  4.11000013 35.45000076]
[ 9.19000053  4.11000013 35.45000076]
[ 9.19000053  4.11000013 35.45000076]
[ 5.82000113  3.99000001 13.94000053]
[ 5.82000113  3.99000001 13.94000053]
[1.20000005 3.         1.63      ]
[1.20000005 3.         1.63      ]
[0.55000001 0.47999999 0.94999999]
[0.55000001 0.47999999 0.94999999]
[0.55000001 0.47999999 0.94999999]
[0.40000001 1.11000001 1.44000006]
[0.40000001 1.11000001 1.44000006]
[0.68000001 1.28999996 1.24000001]
[0.68000001 1.28999996 1.24000001]
[0.68000001 1.28999996 1.24000001]
[0.63999999 1.41999996 0.93000001]
[0.63999999 1.41999996 0.93000001]
[0.63999999 1.69000101 1.61000001]
[0.63999999 1.69000101 1.61000001]
[0.63999999 1.69000101 1.61000001]
[0.63       0.70999998 0.46000001]
[0.63       0.70999998 0.46000001]
[0.63       0.70999998 0.

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[0.95999998 0.69999999 0.62      ]
[0.95999998 0.69999999 0.62      ]
[0.95999998 0.69999999 0.62      ]
[0.63999999 0.89999998 1.07000005]
[0.63999999 0.89999998 1.07000005]
[0.68000001 1.25       0.73000002]
[0.68000001 1.25       0.73000002]
[0.68000001 1.25       0.73000002]
[0.62       1.10000002 0.99000001]
[0.62       1.10000002 0.99000001]
[0.66000003 0.57999998 0.61000001]
[0.66000003 0.57999998 0.61000001]
[0.66000003 0.57999998 0.61000001]
[0.91000003 1.19000006 0.99000001]
[0.91000003 1.19000006 0.99000001]
[0.58999997 0.97000003 0.51999998]
[0.58999997 0.97000003 0.51999998]
[0.58999997 0.97000003 0.51999998]
[1.00999999 1.05999994 1.01999998]
[1.00999999 1.05999994 1.01999998]
[0.70999998 0.74000001 0.81999999]
[0.70999998 0.74000001 0.81999999]
[0.70999998 0.74000001 0.81999999]
[0.57999998 0.74000001 0.75      ]
[0.57999998 0.74000001 0.75      ]
[1.05999994 1.24000001 0.82999998]
[1.05999994 1.24000001 0.82999998]
[1.05999994 1.24000001 0.82999998]
[1.27999997 0.94    

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.


[0.85000002 0.89999998 0.81999999]
[0.85000002 0.89999998 0.81999999]
[0.85000002 0.89999998 0.81999999]
[0.85000002 0.89999998 0.81999999]
[0.85000002 0.89999998 0.81999999]
[0.85000002 0.89999998 0.81999999]
[0.85000002 1.00999999 0.77999997]
[0.85000002 1.00999999 0.77999997]
[0.66000003 0.81999999 0.81999999]
[0.66000003 0.81999999 0.81999999]
[0.66000003 0.81999999 0.81999999]
[0.69999999 0.89999998 0.85000002]
[0.69999999 0.89999998 0.85000002]
[0.89999998 1.07000005 0.82999998]
[0.89999998 1.07000005 0.82999998]
[0.63       1.13999999 0.89999998]
[0.63       1.13999999 0.89999998]
[0.63       1.13999999 0.89999998]
[0.58999997 0.93000001 1.        ]
[0.58999997 0.93000001 1.        ]
[0.58999997 1.01999998 0.82999998]
[0.58999997 1.01999998 0.82999998]
[0.58999997 1.01999998 0.82999998]
[0.81999999 0.93000001 0.63      ]
[0.81999999 0.93000001 0.63      ]
[0.81999999 0.93000001 0.63      ]
[0.79000002 0.88999999 0.92000002]
[0.79000002 0.88999999 0.92000002]
[0.79000002 0.839999

/home/lars/.local/lib/python3.6/site-packages/ipykernel_launcher.py:29: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.



[0.61000001 0.88999999 0.77999997]
[0.75999999 0.95999998 0.89999998]
[0.75999999 0.95999998 0.89999998]
[0.75999999 0.95999998 0.89999998]
[0.75999999 0.91000003 0.58999997]
[0.75999999 0.91000003 0.58999997]
[0.61000001 0.89999998 0.77999997]
[0.61000001 0.89999998 0.77999997]
[0.61000001 0.89999998 0.77999997]
[0.68000001 0.88       0.82999998]
[0.68000001 0.88       0.82999998]
[0.56999999 0.88999999 0.77999997]
[0.56999999 0.88999999 0.77999997]
[0.56999999 0.88999999 0.77999997]
[0.70999998 0.89999998 0.76999998]
[0.74000001 0.97000003 0.86000001]
[0.74000001 0.97000003 0.86000001]
[0.81       0.94999999 0.77999997]
[0.81       0.94999999 0.77999997]
[0.75       0.88       0.76999998]
[0.75       0.88       0.76999998]
[0.75       0.88       0.76999998]
[0.75       0.88       0.76999998]
[0.75       0.88       0.76999998]
[0.86000001 0.75999999 0.72000003]
[0.86000001 0.75999999 0.72000003]
[0.76999998 0.93000001 0.80000001]
[0.76999998 0.93000001 0.80000001]
[0.76999998 0.93000

# !!! Save recorded Data !!!

In [26]:
txs = []
tys = []
tzs = []
rxs = []
rys = []
rzs = []
fxs = []
fys = []
fzs = []
txs = []
tys = []
tzs = []

for i in range(len(observations_rec)):

    txs.append(observations_rec[i][0])
    tys.append(observations_rec[i][1])
    tzs.append(observations_rec[i][2])
    rxs.append(observations_rec[i][3])
    rys.append(observations_rec[i][4])
    rzs.append(observations_rec[i][5])
    fxs.append(observations_rec[i][6])
    fys.append(observations_rec[i][7])
    fzs.append(observations_rec[i][8])
    txs.append(observations_rec[i][9])
    tys.append(observations_rec[i][10])
    tzs.append(observations_rec[i][11])
    
recordings = {
    "tx" : txs,
    "ty" : tys,
    "tz" : tzs,
    "rx" : rxs,
    "ry" : rys,
    "rz" : rzs,
    "fx" : fxs,
    "fy" : fys,
    "fz" : fzs,
    "tx" : txs,
    "ty" : tys,
    "tz" : tzs,
    "Reward" : rewards_rec
}

In [27]:
filename = "{}".format(take).zfill(4)+"_model_{}.json".format(model_number)
with open(os.path.join(*[SAVE_PATH, filename]), 'w') as file:
    json.dump(recordings, file)
    file.close()

In [28]:
observations_rec_df = pandas.DataFrame(observations_rec, columns=["pos1", "pos2", "pos3", "rotx", "roty", "rotz", "Fx", "Fy", "Fz", "Mx", "My", "Mz"])
poses_rec_df = pandas.DataFrame(poses_rec, columns=["tx", "ty", "tz", "rx", "ry", "rz"])
ft_values_rec_df = pandas.DataFrame(ft_values_rec, columns=["Fx", "Fy", "Fz", "Mx", "My", "Mz"])
q_rec_df = pandas.DataFrame(q_rec, columns=["q[0]", "q[1]", "q[2]", "q[3]", "q[4]", "q[5]"])
qd_rec_df = pandas.DataFrame(qd_rec, columns=["qd[0]", "qd[1]", "qd[2]", "qd[3]", "qd[4]", "qd[5]"])
rewards_df = pandas.DataFrame(rewards_rec, columns=["Rewards"])
info_df = pandas.DataFrame(columns=['Steps', 'Reward'], index=[model_name+"_"+str(take)])

info_df.loc[model_name+"_"+str(take), "Steps"] = len(rewards_rec)
info_df.loc[model_name+"_"+str(take), "Reward"] = numpy.sum(rewards_rec)
    
DIRECTORY = os.path.join(*[SAVE_PATH])
observations_rec_df.to_feather(os.path.join(*[SAVE_PATH, "{}".format(take).zfill(4)+"_obs.ftr"]))
poses_rec_df.to_feather(os.path.join(*[SAVE_PATH, "{}".format(take).zfill(4)+"_pose.ftr"]))
ft_values_rec_df.to_feather(os.path.join(*[SAVE_PATH, "{}".format(take).zfill(4)+"_ft.ftr"]))
q_rec_df.to_feather(os.path.join(*[SAVE_PATH, "{}".format(take).zfill(4)+"_q.ftr"]))
qd_rec_df.to_feather(os.path.join(*[SAVE_PATH, "{}".format(take).zfill(4)+"_qd.ftr"]))
rewards_df.to_feather(os.path.join(*[SAVE_PATH, "{}".format(take).zfill(4)+"_reward.ftr"]))
info_df = info_df.reset_index()
info_df.to_feather(os.path.join(*[SAVE_PATH, "{}".format(take).zfill(4)+"_info.ftr"]))

NameError: name 'model_name' is not defined

# --- Visualize the Data with Visualize_Hardware_Tests.ipynb ---