In [1]:
import os
import numpy
import pandas
import json
import matplotlib.pyplot as plt

import rospy
from realsense2_camera.msg import CustomVector

In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In /home/lars/.local/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_c

In [3]:
def observation_callback(data):
    global observations
    observations = numpy.array(data.data)

In [4]:
rospy.init_node("obs_tester", anonymous=True)
rospy.Subscriber("/observation", CustomVector, observation_callback)
rate = rospy.Rate(125)

In [5]:
obs = list()

In [6]:
for i in range(1000):
    rate.sleep()
    obs.append(observations)

In [7]:
obs

[array([ 1.28140435e-01,  2.26163049e-03,  4.79640951e-03, -9.53106093e-04,
        -4.31937893e-04, -2.17478368e-02, -1.14999998e+00,  2.19999999e-01,
        -8.70000005e-01, -1.30000003e-02,  3.70000005e-02,  1.79999992e-02]),
 array([ 1.28195882e-01,  2.26443214e-03,  4.80011990e-03, -9.29923903e-04,
        -3.95751355e-04, -2.17598304e-02, -1.12000000e+00,  2.09999993e-01,
        -8.89999986e-01, -1.30000003e-02,  3.99999991e-02,  1.70000009e-02]),
 array([ 1.28195882e-01,  2.26443214e-03,  4.80011990e-03, -9.29923903e-04,
        -3.95751355e-04, -2.17598304e-02, -1.12000000e+00,  2.09999993e-01,
        -8.89999986e-01, -1.30000003e-02,  3.99999991e-02,  1.70000009e-02]),
 array([ 1.28195882e-01,  2.26443214e-03,  4.80011990e-03, -9.29923903e-04,
        -3.95751355e-04, -2.17598304e-02, -1.12000000e+00,  2.09999993e-01,
        -8.89999986e-01, -1.30000003e-02,  3.99999991e-02,  1.70000009e-02]),
 array([ 1.28195882e-01,  2.26443214e-03,  4.80011990e-03, -9.29923903e-04,
    